import type { PublicApi } from '@/shared/types';
import { v4 as uuid } from 'uuid';

export const MOCK_PUBLIC_APIS: PublicApi[] = [
  {
    id: uuid(),
    name: 'OpenWeatherMap',
    description: 'Current weather data, forecasts, historical data for any location',
    category: ApiCategory.WEATHER,
    url: 'https://openweathermap.org/api',
    docs: 'https://openweathermap.org/api',
    auth: [AuthType.API_KEY],
    https: true,
    cors: true,
    rateLimit: '60 calls/min (free tier)',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Alpha Vantage',
    description: 'Real-time and historical stock market data with technical analysis',
    category: ApiCategory.FINANCE,
    url: 'https://www.alphavantage.co',
    docs: 'https://www.alphavantage.co/documentation',
    auth: [AuthType.API_KEY],
    https: true,
    cors: false,
    rateLimit: '5 calls/min (free tier)',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Twitter API v2',
    description: 'Access tweets, users, and conversation data from Twitter',
    category: ApiCategory.SOCIAL_MEDIA,
    url: 'https://api.twitter.com',
    docs: 'https://developer.twitter.com/en/docs',
    auth: [AuthType.OAUTH_2, AuthType.BEARER_TOKEN],
    https: true,
    cors: false,
    rateLimit: 'Varies by endpoint',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'IP Geolocation API',
    description: 'Get geolocation data, timezone, and ISP info from IP addresses',
    category: ApiCategory.GEOLOCATION,
    url: 'https://ip-api.com',
    docs: 'https://ip-api.com/docs',
    auth: [AuthType.NONE],
    https: true,
    cors: true,
    rateLimit: '45 requests/min',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Etherscan',
    description: 'Ethereum blockchain explorer and analytics data API',
    category: ApiCategory.BLOCKCHAIN,
    url: 'https://etherscan.io/apis',
    docs: 'https://docs.etherscan.io',
    auth: [AuthType.API_KEY],
    https: true,
    cors: true,
    rateLimit: '5 calls/sec',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Stripe API',
    description: 'Payment processing, billing, and financial services',
    category: ApiCategory.PAYMENT,
    url: 'https://stripe.com/docs/api',
    docs: 'https://stripe.com/docs',
    auth: [AuthType.API_KEY, AuthType.BEARER_TOKEN],
    https: true,
    cors: false,
    rateLimit: '100 requests/sec',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'SendGrid',
    description: 'Email delivery platform with transactional and marketing emails',
    category: ApiCategory.EMAIL,
    url: 'https://sendgrid.com/docs/api-reference',
    docs: 'https://sendgrid.com/docs',
    auth: [AuthType.BEARER_TOKEN],
    https: true,
    cors: false,
    rateLimit: 'Depends on plan',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Twilio',
    description: 'SMS, voice, video, and messaging communications platform',
    category: ApiCategory.SMS,
    url: 'https://www.twilio.com/docs/api',
    docs: 'https://www.twilio.com/docs',
    auth: [AuthType.BASIC],
    https: true,
    cors: false,
    rateLimit: 'No hard limit',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Google Maps API',
    description: 'Maps, geocoding, directions, and places information',
    category: ApiCategory.MAPPING,
    url: 'https://developers.google.com/maps',
    docs: 'https://developers.google.com/maps/documentation',
    auth: [AuthType.API_KEY],
    https: true,
    cors: true,
    rateLimit: 'Per-plan based',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Google Analytics Data API',
    description: 'Access analytics data about website traffic and user behavior',
    category: ApiCategory.ANALYTICS,
    url: 'https://developers.google.com/analytics/devguides/reporting/data/v1',
    docs: 'https://developers.google.com/analytics',
    auth: [AuthType.OAUTH_2],
    https: true,
    cors: false,
    rateLimit: '10,000 per day per property',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Salesforce CRM API',
    description: 'Customer relationship management data and workflow automation',
    category: ApiCategory.CRM,
    url: 'https://developer.salesforce.com/docs/apis/rest',
    docs: 'https://developer.salesforce.com',
    auth: [AuthType.OAUTH_2],
    https: true,
    cors: false,
    rateLimit: '15,000 per 24 hours',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Google Translate API',
    description: 'Machine translation supporting 100+ languages',
    category: ApiCategory.TRANSLATION,
    url: 'https://cloud.google.com/translate',
    docs: 'https://cloud.google.com/translate/docs',
    auth: [AuthType.API_KEY],
    https: true,
    cors: false,
    rateLimit: 'Per-plan based',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'IBM Watson NLU',
    description: 'Natural language understanding including sentiment, entities, and keywords',
    category: ApiCategory.NLP,
    url: 'https://www.ibm.com/cloud/watson-natural-language-understanding',
    docs: 'https://cloud.ibm.com/apidocs',
    auth: [AuthType.BEARER_TOKEN],
    https: true,
    cors: false,
    rateLimit: 'Depends on plan',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Face++ (Megvii)',
    description: 'Face detection, recognition, and verification API',
    category: ApiCategory.IMAGE_RECOGNITION,
    url: 'https://www.faceplusplus.com',
    docs: 'https://www.faceplusplus.com/api-overview',
    auth: [AuthType.API_KEY],
    https: true,
    cors: false,
    rateLimit: '1 call/sec (free tier)',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'NewsAPI',
    description: 'Breaking news headlines and articles from news sources worldwide',
    category: ApiCategory.NEWS,
    url: 'https://newsapi.org',
    docs: 'https://newsapi.org/docs',
    auth: [AuthType.API_KEY],
    https: true,
    cors: true,
    rateLimit: '100 requests/day (free)',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'CoinGecko API',
    description: 'Cryptocurrency market data, charts, and historical information',
    category: ApiCategory.CRYPTO,
    url: 'https://www.coingecko.com/api',
    docs: 'https://www.coingecko.com/en/api/documentation',
    auth: [AuthType.NONE, AuthType.API_KEY],
    https: true,
    cors: true,
    rateLimit: '50 calls/minute',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Exchange Rates API',
    description: 'Real-time currency exchange rates and historical data',
    category: ApiCategory.EXCHANGE_RATES,
    url: 'https://exchangerate-api.com',
    docs: 'https://www.exchangerate-api.com/docs',
    auth: [AuthType.API_KEY],
    https: true,
    cors: true,
    rateLimit: '1,500 per month (free)',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'ESPN API',
    description: 'Sports data including scores, schedules, standings, and statistics',
    category: ApiCategory.SPORTS,
    url: 'https://www.espn.com/apis/site/v2',
    docs: 'https://www.espn.com/apis/site/v2',
    auth: [AuthType.NONE],
    https: true,
    cors: true,
    rateLimit: 'No formal limit published',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'The Movie Database (TMDb)',
    description: 'Movies, TV shows, actors, and entertainment data',
    category: ApiCategory.MOVIES,
    url: 'https://www.themoviedb.org/api',
    docs: 'https://developers.themoviedb.org/3',
    auth: [AuthType.API_KEY],
    https: true,
    cors: true,
    rateLimit: '40 requests/10 seconds',
    freeTier: true,
  },
  {
    id: uuid(),
    name: 'Spotify Web API',
    description: 'Music streaming data, playlists, albums, tracks, and recommendations',
    category: ApiCategory.MUSIC,
    url: 'https://developer.spotify.com/documentation/web-api',
    docs: 'https://developer.spotify.com',
    auth: [AuthType.OAUTH_2],
    https: true,
    cors: false,
    rateLimit: 'Rate limiting applies',
    freeTier: true,
  },
];
