import type { Coin } from '@/entities/coin/model/types';

export const mockCoins: Coin[] = [
  {
    id: 'bitcoin',
    rank: 1,
    name: 'Bitcoin',
    symbol: 'BTC',
    price: 68420,
    change24h: 2.4,
    marketCap: 1340000000000,
    volume24h: 28500000000,
    circulatingSupply: 19710000,
    maxSupply: 21000000,
    category: 'Store of Value',
    risk: 'Low',
    description: 'Digital reserve asset with strongest liquidity and institutional demand.',
    website: 'https://bitcoin.org',
    thesis: 'Core benchmark asset for market sentiment and risk rotation.',
    tags: ['macro', 'etf', 'store-of-value'],
  },
  {
    id: 'ethereum',
    rank: 2,
    name: 'Ethereum',
    symbol: 'ETH',
    price: 3525,
    change24h: 1.6,
    marketCap: 423000000000,
    volume24h: 17400000000,
    circulatingSupply: 120100000,
    category: 'Layer 1',
    risk: 'Low',
    description: 'Smart contract leader powering DeFi, NFT, and rollup ecosystems.',
    website: 'https://ethereum.org',
    thesis: 'Best proxy for onchain activity and app-layer adoption.',
    tags: ['smart-contracts', 'staking', 'rollups'],
  },
  {
    id: 'solana',
    rank: 3,
    name: 'Solana',
    symbol: 'SOL',
    price: 168.3,
    change24h: 5.8,
    marketCap: 74800000000,
    volume24h: 4900000000,
    circulatingSupply: 444000000,
    category: 'Layer 1',
    risk: 'Medium',
    description: 'High-throughput chain with strong retail flows and consumer app momentum.',
    website: 'https://solana.com',
    thesis: 'Momentum leader when market rewards growth and speculative activity.',
    tags: ['consumer', 'throughput', 'memecoins'],
  },
  {
    id: 'chainlink',
    rank: 4,
    name: 'Chainlink',
    symbol: 'LINK',
    price: 17.82,
    change24h: -1.2,
    marketCap: 10400000000,
    volume24h: 680000000,
    circulatingSupply: 587000000,
    maxSupply: 1000000000,
    category: 'DeFi',
    risk: 'Medium',
    description: 'Oracle network connecting blockchains with external data and messaging.',
    website: 'https://chain.link',
    thesis: 'Infra bet on tokenized RWAs and cross-chain messaging.',
    tags: ['oracles', 'infra', 'rwa'],
  },
  {
    id: 'uniswap',
    rank: 5,
    name: 'Uniswap',
    symbol: 'UNI',
    price: 10.47,
    change24h: 3.1,
    marketCap: 6300000000,
    volume24h: 295000000,
    circulatingSupply: 598000000,
    maxSupply: 1000000000,
    category: 'DeFi',
    risk: 'Medium',
    description: 'Leading decentralized exchange token tied to onchain trading activity.',
    website: 'https://uniswap.org',
    thesis: 'Pure expression of DeFi volume and governance optionality.',
    tags: ['dex', 'defi', 'governance'],
  },
  {
    id: 'binance-coin',
    rank: 6,
    name: 'BNB',
    symbol: 'BNB',
    price: 598.2,
    change24h: 0.9,
    marketCap: 88400000000,
    volume24h: 1900000000,
    circulatingSupply: 147600000,
    maxSupply: 200000000,
    category: 'Exchange',
    risk: 'Medium',
    description: 'Exchange ecosystem token with burn mechanics and broad utility.',
    website: 'https://www.bnbchain.org',
    thesis: 'Cash-flow-like proxy for exchange and chain usage.',
    tags: ['exchange', 'burn', 'utility'],
  },
  {
    id: 'dogecoin',
    rank: 7,
    name: 'Dogecoin',
    symbol: 'DOGE',
    price: 0.16,
    change24h: 7.4,
    marketCap: 23100000000,
    volume24h: 1850000000,
    circulatingSupply: 144300000000,
    category: 'Meme',
    risk: 'High',
    description: 'Large-cap meme coin driven by social attention and liquidity bursts.',
    website: 'https://dogecoin.com',
    thesis: 'High-beta sentiment gauge for speculative retail appetite.',
    tags: ['meme', 'social', 'beta'],
  },
  {
    id: 'render',
    rank: 8,
    name: 'Render',
    symbol: 'RNDR',
    price: 9.73,
    change24h: -2.8,
    marketCap: 3780000000,
    volume24h: 212000000,
    circulatingSupply: 388000000,
    maxSupply: 536000000,
    category: 'AI',
    risk: 'High',
    description: 'Distributed GPU rendering network tied to AI and creator narratives.',
    website: 'https://rendernetwork.com',
    thesis: 'Narrative-sensitive alt for AI infrastructure exposure.',
    tags: ['ai', 'gpu', 'narrative'],
  },
  {
    id: 'injective',
    rank: 9,
    name: 'Injective',
    symbol: 'INJ',
    price: 28.64,
    change24h: 4.3,
    marketCap: 2670000000,
    volume24h: 168000000,
    circulatingSupply: 93300000,
    maxSupply: 100000000,
    category: 'DeFi',
    risk: 'High',
    description: 'App-specific chain focused on derivatives, RWAs, and onchain finance.',
    website: 'https://injective.com',
    thesis: 'Higher-risk growth bet on specialized DeFi infrastructure.',
    tags: ['derivatives', 'app-chain', 'growth'],
  },
  {
    id: 'arbitrum',
    rank: 10,
    name: 'Arbitrum',
    symbol: 'ARB',
    price: 1.08,
    change24h: -0.7,
    marketCap: 3060000000,
    volume24h: 402000000,
    circulatingSupply: 2840000000,
    maxSupply: 10000000000,
    category: 'Layer 1',
    risk: 'Medium',
    description: 'Rollup ecosystem token exposed to Ethereum scaling and ecosystem growth.',
    website: 'https://arbitrum.io',
    thesis: 'Infra allocation for lower-fee onchain execution growth.',
    tags: ['rollup', 'ethereum', 'scaling'],
  },
];
